# Generated by Django 4.2.5 on 2023-12-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(default='', max_length=50)),
                ('answer_txt', models.TextField(default='')),
                ('date', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
