# Generated by Django 4.2.5 on 2023-09-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_pic_news_picname_news_picurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
