# Generated by Django 4.2.5 on 2023-12-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='random',
            field=models.IntegerField(default=0),
        ),
    ]
