# Generated by Django 4.2.5 on 2023-12-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_random'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='random',
            new_name='rand',
        ),
    ]
