# Generated by Django 4.2.5 on 2023-09-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_main_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='short_about',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
