# Generated by Django 4.2.5 on 2024-01-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_main_short_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='seo_key_words',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='seo_txt',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
